name: launch_at_startup_example
description: Demonstrates how to use the launch_at_startup plugin.
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  launch_at_startup:
    path: ../
  cupertino_icons: ^1.0.2
  bot_toast: ^4.0.1
  package_info_plus: ^7.0.0
  preference_list: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  msix: ^3.16.7

flutter:
  uses-material-design: true

msix_config:
  display_name: launch_at_startup_example
  publisher_display_name: LeanFlutter
  identity_name: dev.leanflutter.examples.launchatstartupexample
  msix_version: 1.0.0.0
